---
title: Letter to the Editor
author: "Not just for programmers: How GitHub can accelerate collaborative and reproducible research in ecology and evolution"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: cosmo 
    highlight: tango
    self_contained: true
---
```{r include=FALSE}
knitr::opts_chunk$set(fig.retina = 2)
```

Dear Editor,

We would like to submit our manuscript entitled “Not just for programmers: How GitHub can accelerate collaborative and reproducible research in ecology and evolution” for consideration to be published in *Methods in Ecology and Evolution*. 
Our study provides researchers with a critical review of thirteen practical ways they can use GitHub – an online, cloud-based service for cooperative and documented code development – to make their research more collaborative, transparent, and reproducible.

Most scientists, including researchers in ecology and evolutionary biology, have become critically dependent on computational tools in their research.
This code-dependent workflow imposes steep requirements towards an efficient, well-documented process in the publication and collaboration of maintainable scientific code.
Albeit, many researchers lack exposure to adequate software development practices and thus are required to dedicate valuable time and effort to learning how to use research-facilitating tools.
Formal academic courses on these types of tools are often unavailable and researchers are left to learn through informal blogs, videos, and other online forums.
This may present a plethora of practical barriers to applying adequate standards to maintaining scientific code.

The adoption of GitHub in ecology and evolutionary biology workflows is not widespread in part because there have been only a few disparate attempts at creating domain-specific information and guidelines.
In our study, we review and discuss one of the most used web-based platforms for computational version control and collaboration, GitHub, and provide researchers in ecology and evolution with comprehensive and practical workflows aimed at facilitating their scientific code and management process.

Our manuscript is the most accessible and practical guide to using GitHub in ecology and evolution research to date.
We build upon our own experiences (as an international collaboration from authors across many ecology and evolution subdisciplines) and on existing resources mainly targeted at other disciplines, to highlight how researchers can use the readily available GitHub suite to make their research practices reproducible, collaborative, and transparent.
Our manuscript is important for the *Methods in Ecology and Evolution* readership because researchers in ecology and evolutionary biology can greatly benefit from our perspectives to migrate and incorporate GitHub workflows in their research practices ultimately towards an open and collaborative science.
Our manuscript also complements recently published literature outlining how the ongoing adoption of Open Science practices is transforming research in ecology and evolutionary biology.

The enclosed manuscript is available as a preprint on the MetaArXiv server (https://www.doi.org/10.31222/osf.io/x3p2q), with over 440 downloads and 2,400 views in four months. 
We declare that our study is not published or under consideration for publication elsewhere.

All authors have contributed and reviewed the current version of the manuscript and agreed to its submission to Methods in Ecology and Evolution.

We appreciate your time and consideration of our manuscript for publication in your journal.

Sincerely,

Pedro Henrique Pereira Braga, on behalf of all co-authors

---

We would like to suggest the following potential reviewers for our manuscript:
- 
- 
- 
